-- MySQL Script generated by MySQL Workbench
-- Fri Oct 17 01:57:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rejestracja_bankowa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rejestracja_bankowa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rejestracja_bankowa` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `rejestracja_bankowa` ;

-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Rejes.`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Rejes.` (
  `Imię` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `PESEL` VARCHAR(11) NOT NULL,
  `Hasło` VARCHAR(45) NOT NULL,
  `Login_użyt.` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Imię`, `Login_użyt.`, `Nazwisko`, `Hasło`, `PESEL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`D._klienta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`D._klienta` (
  `Data_urodzenia` DATE NOT NULL,
  `Stan_cywilny` VARCHAR(8) NOT NULL,
  `Adres_zamieszkania` VARCHAR(50) NOT NULL,
  `Miejsce_zatrudnienia` VARCHAR(45) NOT NULL,
  `Miesięczne_przychody` DECIMAL(10,2) NOT NULL,
  `Typ_uowy_zatrudnienia` VARCHAR(45) NOT NULL,
  `Nr_id_klienta` VARCHAR(45) NOT NULL,
  `Rejes._Imię` VARCHAR(45) NOT NULL,
  `Rejes._Login_użyt.` VARCHAR(45) NOT NULL,
  `Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  `Rejes._Hasło` VARCHAR(45) NOT NULL,
  `Rejes._PESEL` VARCHAR(11) NOT NULL,
  UNIQUE INDEX `Nr_id_klienta_UNIQUE` (`Nr_id_klienta` ASC),
  PRIMARY KEY (`Nr_id_klienta`, `Rejes._Imię`, `Rejes._Login_użyt.`, `Rejes._PESEL`, `Rejes._Hasło`, `Rejes._Nazwisko`),
  INDEX `fk_D._klienta_Rejes.1_idx` (`Rejes._Imię` ASC, `Rejes._Login_użyt.` ASC, `Rejes._Nazwisko` ASC, `Rejes._Hasło` ASC, `Rejes._PESEL` ASC),
  CONSTRAINT `fk_D._klienta_Rejes.1`
    FOREIGN KEY (`Rejes._Imię` , `Rejes._Login_użyt.` , `Rejes._Nazwisko` , `Rejes._Hasło` , `Rejes._PESEL`)
    REFERENCES `rejestracja_bankowa`.`Rejes.` (`Imię` , `Login_użyt.` , `Nazwisko` , `Hasło` , `PESEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Poś_dn.`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Poś_dn.` (
  `D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._Login_użyt.` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._PESEL` VARCHAR(11) NOT NULL,
  `D._klienta_Rejes._Hasło` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  INDEX `fk_Poś_danych_D._klienta1_idx` (`D._klienta_Nr_id_klienta` ASC, `D._klienta_Rejes._Imię` ASC, `D._klienta_Rejes._Login_użyt.` ASC, `D._klienta_Rejes._PESEL` ASC, `D._klienta_Rejes._Hasło` ASC, `D._klienta_Rejes._Nazwisko` ASC),
  PRIMARY KEY (`D._klienta_Nr_id_klienta`, `D._klienta_Rejes._Imię`, `D._klienta_Rejes._Nazwisko`),
  CONSTRAINT `fk_Poś_danych_D._klienta1`
    FOREIGN KEY (`D._klienta_Nr_id_klienta` , `D._klienta_Rejes._Imię` , `D._klienta_Rejes._Login_użyt.` , `D._klienta_Rejes._PESEL` , `D._klienta_Rejes._Hasło` , `D._klienta_Rejes._Nazwisko`)
    REFERENCES `rejestracja_bankowa`.`D._klienta` (`Nr_id_klienta` , `Rejes._Imię` , `Rejes._Login_użyt.` , `Rejes._PESEL` , `Rejes._Hasło` , `Rejes._Nazwisko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Stat_trans.`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Stat_trans.` (
  `Status_trans.` ENUM('bieżący') NOT NULL,
  `Postęp_trans.` TINYINT(0) NOT NULL,
  PRIMARY KEY (`Status_trans.`, `Postęp_trans.`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`P_bieżący`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`P_bieżący` (
  `Typ_transakcji` VARCHAR(45) NOT NULL,
  `Tytuł_przelewu` VARCHAR(45) NOT NULL,
  `Nr_konta_odbiorcy` VARCHAR(50) NOT NULL,
  `Bank_odbiorcy` VARCHAR(45) NOT NULL,
  `Kwota_trans.` DECIMAL(10,2) NOT NULL,
  `Termin_trans.` DATE NOT NULL,
  `Saldo_pretrans.` DECIMAL(10,2) NOT NULL,
  `Poś_dn._D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  `Poś_dn._D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `Poś_dn._D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  `Stat_trans._Status_trans.` ENUM('bieżący') NOT NULL,
  `Stat_trans._Postęp_trans.` TINYINT(0) NOT NULL,
  PRIMARY KEY (`Typ_transakcji`, `Tytuł_przelewu`, `Nr_konta_odbiorcy`, `Termin_trans.`, `Kwota_trans.`, `Bank_odbiorcy`, `Saldo_pretrans.`, `Poś_dn._D._klienta_Rejes._Nazwisko`, `Poś_dn._D._klienta_Rejes._Imię`, `Poś_dn._D._klienta_Nr_id_klienta`),
  UNIQUE INDEX `Nr_konta_odbiorcy_UNIQUE` (`Nr_konta_odbiorcy` ASC),
  UNIQUE INDEX `Typ_transakcji_UNIQUE` (`Typ_transakcji` ASC) ,
  UNIQUE INDEX `Tytuł_przelewu_UNIQUE` (`Tytuł_przelewu` ASC) ,
  UNIQUE INDEX `Kwota_transakcji_UNIQUE` (`Kwota_trans.` ASC) ,
  UNIQUE INDEX `Bank_odbiorcy_UNIQUE` (`Bank_odbiorcy` ASC) ,
  UNIQUE INDEX `Termin_transakcji_UNIQUE` (`Termin_trans.` ASC) ,
  UNIQUE INDEX `Saldo_pretransakcyjne_UNIQUE` (`Saldo_pretrans.` ASC),
  INDEX `fk_P_bieżący_Poś_dn.1_idx` (`Poś_dn._D._klienta_Nr_id_klienta` ASC, `Poś_dn._D._klienta_Rejes._Imię` ASC, `Poś_dn._D._klienta_Rejes._Nazwisko` ASC),
  INDEX `fk_P_bieżący_Stat_trans.1_idx` (`Stat_trans._Status_trans.` ASC, `Stat_trans._Postęp_trans.` ASC) ,
  CONSTRAINT `fk_P_bieżący_Poś_dn.1`
    FOREIGN KEY (`Poś_dn._D._klienta_Nr_id_klienta` , `Poś_dn._D._klienta_Rejes._Imię` , `Poś_dn._D._klienta_Rejes._Nazwisko`)
    REFERENCES `rejestracja_bankowa`.`Poś_dn.` (`D._klienta_Nr_id_klienta` , `D._klienta_Rejes._Imię` , `D._klienta_Rejes._Nazwisko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P_bieżący_Stat_trans.1`
    FOREIGN KEY (`Stat_trans._Status_trans.` , `Stat_trans._Postęp_trans.`)
    REFERENCES `rejestracja_bankowa`.`Stat_trans.` (`Status_trans.` , `Postęp_trans.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Stat_trans2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Stat_trans2` (
  `Status_trans.` ENUM('zrealizowany') NOT NULL,
  `Postęp_trans.` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Status_trans.`, `Postęp_trans.`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Poś_trans.`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Poś_trans.` (
  `P_bieżący_Typ_transakcji` VARCHAR(45) NOT NULL,
  `P_bieżący_Tytuł_przelewu` VARCHAR(45) NOT NULL,
  `P_bieżący_Nr_konta_odbiorcy` VARCHAR(50) NOT NULL,
  `P_bieżący_Termin_trans.` DATE NOT NULL,
  `P_bieżący_Kwota_trans.` DECIMAL(10,2) NOT NULL,
  `P_bieżący_Bank_odbiorcy` VARCHAR(45) NOT NULL,
  `P_bieżący_Saldo_pretrans.` DECIMAL(10,2) NOT NULL,
  `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  `Stat_trans2_Status_trans.` ENUM('zrealizowany') NOT NULL,
  `Stat_trans2_Postęp_trans.` TINYINT(1) NOT NULL,
  INDEX `fk_Poś_trans._P_bieżący1_idx` (`P_bieżący_Typ_transakcji` ASC, `P_bieżący_Tytuł_przelewu` ASC, `P_bieżący_Nr_konta_odbiorcy` ASC, `P_bieżący_Termin_trans.` ASC, `P_bieżący_Kwota_trans.` ASC, `P_bieżący_Bank_odbiorcy` ASC, `P_bieżący_Saldo_pretrans.` ASC, `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` ASC, `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` ASC, `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` ASC),
  INDEX `fk_Poś_trans._Stat_trans21_idx` (`Stat_trans2_Status_trans.` ASC, `Stat_trans2_Postęp_trans.` ASC) ,
  PRIMARY KEY (`P_bieżący_Typ_transakcji`, `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta`, `P_bieżący_Poś_dn._D._klienta_Rejes._Imię`, `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko`, `P_bieżący_Saldo_pretrans.`, `P_bieżący_Bank_odbiorcy`, `P_bieżący_Kwota_trans.`, `P_bieżący_Termin_trans.`, `P_bieżący_Nr_konta_odbiorcy`, `P_bieżący_Tytuł_przelewu`, `Stat_trans2_Postęp_trans.`, `Stat_trans2_Status_trans.`),
  CONSTRAINT `fk_Poś_trans._P_bieżący1`
    FOREIGN KEY (`P_bieżący_Typ_transakcji` , `P_bieżący_Tytuł_przelewu` , `P_bieżący_Nr_konta_odbiorcy` , `P_bieżący_Termin_trans.` , `P_bieżący_Kwota_trans.` , `P_bieżący_Bank_odbiorcy` , `P_bieżący_Saldo_pretrans.` , `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` , `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` , `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta`)
    REFERENCES `rejestracja_bankowa`.`P_bieżący` (`Typ_transakcji` , `Tytuł_przelewu` , `Nr_konta_odbiorcy` , `Termin_trans.` , `Kwota_trans.` , `Bank_odbiorcy` , `Saldo_pretrans.` , `Poś_dn._D._klienta_Rejes._Nazwisko` , `Poś_dn._D._klienta_Rejes._Imię` , `Poś_dn._D._klienta_Nr_id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poś_trans._Stat_trans21`
    FOREIGN KEY (`Stat_trans2_Status_trans.` , `Stat_trans2_Postęp_trans.`)
    REFERENCES `rejestracja_bankowa`.`Stat_trans2` (`Status_trans.` , `Postęp_trans.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`P_zreal.`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`P_zreal.` (
  `Poś_trans._P_bieżący_Typ_transakcji` VARCHAR(45) NOT NULL,
  `Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  `Poś_trans._P_bieżący_Saldo_pretrans.` DECIMAL(10,2) NOT NULL,
  `Poś_trans._P_bieżący_Bank_odbiorcy` VARCHAR(45) NOT NULL,
  `Poś_trans._P_bieżący_Kwota_trans.` DECIMAL(10,2) NOT NULL,
  `Poś_trans._P_bieżący_Termin_trans.` DATE NOT NULL,
  `Poś_trans._P_bieżący_Nr_konta_odbiorcy` VARCHAR(50) NOT NULL,
  `Poś_trans._P_bieżący_Tytuł_przelewu` VARCHAR(45) NOT NULL,
  `Poś_trans._Stat_trans2_Postęp_trans.` TINYINT(1) NOT NULL,
  `Poś_trans._Stat_trans2_Status_trans.` ENUM('zrealizowany') NOT NULL,
  INDEX `fk_P_zreal._Poś_trans.1_idx` (`Poś_trans._P_bieżący_Typ_transakcji` ASC, `Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` ASC, `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` ASC, `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` ASC, `Poś_trans._P_bieżący_Saldo_pretrans.` ASC, `Poś_trans._P_bieżący_Bank_odbiorcy` ASC, `Poś_trans._P_bieżący_Kwota_trans.` ASC, `Poś_trans._P_bieżący_Termin_trans.` ASC, `Poś_trans._P_bieżący_Nr_konta_odbiorcy` ASC, `Poś_trans._P_bieżący_Tytuł_przelewu` ASC, `Poś_trans._Stat_trans2_Postęp_trans.` ASC, `Poś_trans._Stat_trans2_Status_trans.` ASC),
  PRIMARY KEY (`Poś_trans._P_bieżący_Typ_transakcji`, `Poś_trans._Stat_trans2_Postęp_trans.`, `Poś_trans._Stat_trans2_Status_trans.`, `Poś_trans._P_bieżący_Tytuł_przelewu`, `Poś_trans._P_bieżący_Nr_konta_odbiorcy`, `Poś_trans._P_bieżący_Termin_trans.`, `Poś_trans._P_bieżący_Kwota_trans.`, `Poś_trans._P_bieżący_Bank_odbiorcy`, `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko`, `Poś_trans._P_bieżący_Saldo_pretrans.`, `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię`, `Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta`),
  CONSTRAINT `fk_P_zreal._Poś_trans.1`
    FOREIGN KEY (`Poś_trans._P_bieżący_Typ_transakcji` , `Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` , `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` , `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` , `Poś_trans._P_bieżący_Saldo_pretrans.` , `Poś_trans._P_bieżący_Bank_odbiorcy` , `Poś_trans._P_bieżący_Kwota_trans.` , `Poś_trans._P_bieżący_Termin_trans.` , `Poś_trans._P_bieżący_Nr_konta_odbiorcy` , `Poś_trans._P_bieżący_Tytuł_przelewu` , `Poś_trans._Stat_trans2_Postęp_trans.` , `Poś_trans._Stat_trans2_Status_trans.`)
    REFERENCES `rejestracja_bankowa`.`Poś_trans.` (`P_bieżący_Typ_transakcji` , `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` , `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` , `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` , `P_bieżący_Saldo_pretrans.` , `P_bieżący_Bank_odbiorcy` , `P_bieżący_Kwota_trans.` , `P_bieżący_Termin_trans.` , `P_bieżący_Nr_konta_odbiorcy` , `P_bieżący_Tytuł_przelewu` , `Stat_trans2_Postęp_trans.` , `Stat_trans2_Status_trans.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Rach_bankowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Rach_bankowe` (
  `P_bieżący_Typ_transakcji` VARCHAR(45) NOT NULL,
  `P_bieżący_Tytuł_przelewu` VARCHAR(45) NOT NULL,
  `P_bieżący_Nr_konta_odbiorcy` VARCHAR(50) NOT NULL,
  `P_bieżący_Termin_trans.` DATE NOT NULL,
  `P_bieżący_Kwota_trans.` DECIMAL(10,2) NOT NULL,
  `P_bieżący_Bank_odbiorcy` VARCHAR(45) NOT NULL,
  `P_bieżący_Saldo_pretrans.` DECIMAL(10,2) NOT NULL,
  `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Typ_transakcji` VARCHAR(45) NOT NULL,
  `P_zreal._Poś_trans._Stat_trans2_Postęp_trans.` TINYINT(1) NOT NULL,
  `P_zreal._Poś_trans._Stat_trans2_Status_trans.` ENUM('zrealizowany') NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Tytuł_przelewu` VARCHAR(45) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Nr_konta_odbiorcy` VARCHAR(50) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Termin_trans.` DATE NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Kwota_trans.` DECIMAL(10,2) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Bank_odbiorcy` VARCHAR(45) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Saldo_pretrans.` DECIMAL(10,2) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  INDEX `fk_Rach_bankowe_P_bieżący1_idx` (`P_bieżący_Typ_transakcji` ASC, `P_bieżący_Tytuł_przelewu` ASC, `P_bieżący_Nr_konta_odbiorcy` ASC, `P_bieżący_Termin_trans.` ASC, `P_bieżący_Kwota_trans.` ASC, `P_bieżący_Bank_odbiorcy` ASC, `P_bieżący_Saldo_pretrans.` ASC, `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` ASC, `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` ASC, `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` ASC),
  INDEX `fk_Rach_bankowe_P_zreal.1_idx` (`P_zreal._Poś_trans._P_bieżący_Typ_transakcji` ASC, `P_zreal._Poś_trans._Stat_trans2_Postęp_trans.` ASC, `P_zreal._Poś_trans._Stat_trans2_Status_trans.` ASC, `P_zreal._Poś_trans._P_bieżący_Tytuł_przelewu` ASC, `P_zreal._Poś_trans._P_bieżący_Nr_konta_odbiorcy` ASC, `P_zreal._Poś_trans._P_bieżący_Termin_trans.` ASC, `P_zreal._Poś_trans._P_bieżący_Kwota_trans.` ASC, `P_zreal._Poś_trans._P_bieżący_Bank_odbiorcy` ASC, `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` ASC, `P_zreal._Poś_trans._P_bieżący_Saldo_pretrans.` ASC, `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` ASC, `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta` ASC),
  CONSTRAINT `fk_Rach_bankowe_P_bieżący1`
    FOREIGN KEY (`P_bieżący_Typ_transakcji` , `P_bieżący_Tytuł_przelewu` , `P_bieżący_Nr_konta_odbiorcy` , `P_bieżący_Termin_trans.` , `P_bieżący_Kwota_trans.` , `P_bieżący_Bank_odbiorcy` , `P_bieżący_Saldo_pretrans.` , `P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` , `P_bieżący_Poś_dn._D._klienta_Rejes._Imię` , `P_bieżący_Poś_dn._D._klienta_Nr_id_klienta`)
    REFERENCES `rejestracja_bankowa`.`P_bieżący` (`Typ_transakcji` , `Tytuł_przelewu` , `Nr_konta_odbiorcy` , `Termin_trans.` , `Kwota_trans.` , `Bank_odbiorcy` , `Saldo_pretrans.` , `Poś_dn._D._klienta_Rejes._Nazwisko` , `Poś_dn._D._klienta_Rejes._Imię` , `Poś_dn._D._klienta_Nr_id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rach_bankowe_P_zreal.1`
    FOREIGN KEY (`P_zreal._Poś_trans._P_bieżący_Typ_transakcji` , `P_zreal._Poś_trans._Stat_trans2_Postęp_trans.` , `P_zreal._Poś_trans._Stat_trans2_Status_trans.` , `P_zreal._Poś_trans._P_bieżący_Tytuł_przelewu` , `P_zreal._Poś_trans._P_bieżący_Nr_konta_odbiorcy` , `P_zreal._Poś_trans._P_bieżący_Termin_trans.` , `P_zreal._Poś_trans._P_bieżący_Kwota_trans.` , `P_zreal._Poś_trans._P_bieżący_Bank_odbiorcy` , `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` , `P_zreal._Poś_trans._P_bieżący_Saldo_pretrans.` , `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` , `P_zreal._Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta`)
    REFERENCES `rejestracja_bankowa`.`P_zreal.` (`Poś_trans._P_bieżący_Typ_transakcji` , `Poś_trans._Stat_trans2_Postęp_trans.` , `Poś_trans._Stat_trans2_Status_trans.` , `Poś_trans._P_bieżący_Tytuł_przelewu` , `Poś_trans._P_bieżący_Nr_konta_odbiorcy` , `Poś_trans._P_bieżący_Termin_trans.` , `Poś_trans._P_bieżący_Kwota_trans.` , `Poś_trans._P_bieżący_Bank_odbiorcy` , `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Nazwisko` , `Poś_trans._P_bieżący_Saldo_pretrans.` , `Poś_trans._P_bieżący_Poś_dn._D._klienta_Rejes._Imię` , `Poś_trans._P_bieżący_Poś_dn._D._klienta_Nr_id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rejestracja_bankowa`.`Uwierzytelnienie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rejestracja_bankowa`.`Uwierzytelnienie` (
  `D._klienta_Nr_id_klienta` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._Imię` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._Login_użyt.` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._PESEL` VARCHAR(11) NOT NULL,
  `D._klienta_Rejes._Hasło` VARCHAR(45) NOT NULL,
  `D._klienta_Rejes._Nazwisko` VARCHAR(45) NOT NULL,
  INDEX `fk_Uwierzytelnienie_D._klienta1_idx` (`D._klienta_Nr_id_klienta` ASC, `D._klienta_Rejes._Imię` ASC, `D._klienta_Rejes._Login_użyt.` ASC, `D._klienta_Rejes._PESEL` ASC, `D._klienta_Rejes._Hasło` ASC, `D._klienta_Rejes._Nazwisko` ASC),
  CONSTRAINT `fk_Uwierzytelnienie_D._klienta1`
    FOREIGN KEY (`D._klienta_Nr_id_klienta` , `D._klienta_Rejes._Imię` , `D._klienta_Rejes._Login_użyt.` , `D._klienta_Rejes._PESEL` , `D._klienta_Rejes._Hasło` , `D._klienta_Rejes._Nazwisko`)
    REFERENCES `rejestracja_bankowa`.`D._klienta` (`Nr_id_klienta` , `Rejes._Imię` , `Rejes._Login_użyt.` , `Rejes._PESEL` , `Rejes._Hasło` , `Rejes._Nazwisko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
